### ISSUE TITLE
Dependency to unix

### ISSUE THREAD

**Issue by s4kas** [stevenroose/gonfig#15]
Hi Steven,

I just updated gonfig to the last version and in a windows machine i'm having the following error:
..\..\..\stevenroose\gonfig\help.go:210: undefined: windows.IoctlGetWinsize
..\..\..\stevenroose\gonfig\help.go:210: undefined: windows.TIOCGWINSZ

I thinks it's because of the unix dependency you added in the help.go file. I rolledback to the commit 7e28f73969512b75a2cd7847444a44d67312f917 and it's working correctly.

BTW, good job on the project, especially the newly added feature to support maps ;)

**Comment by stevenroose** [comment]
Whoops. I don't know why, but I assumed that unix thing would return 0 on
non-unix machines.

That's a pity. I'll look at it tomorrow, try to find a cross-platform
solution. Was most certainly not my intention to rule out the lesser OSes
in the world ;)

**Comment by stevenroose** [comment]
Can you check if https://github.com/stevenroose/gonfig/pull/16 solves the problem? I don't have a Windows machine at my disposal, so I can't test it myself.

**Comment by s4kas** [comment]
Yeap, it works :)
