### ISSUE TITLE
Add option to accept parameters from command line OR file

### ISSUE THREAD

**Issue by raff** [stevenroose/gonfig#2]
Currently if FileDisable=false gonfig.Load fails even if there are command line options.

I guess what I want is actually the option to say "accept options from anywhere" (maybe change *Disable to *Required ?). 

The ideal would be that unless a special input (file, env, flag) you should accept options from wherever they are available, with a certain order:
- read from file 
- read from environment
- read from flag 
so that flags always override env, that always override file (again, unless one or more inputs are required)

**Comment by stevenroose** [comment]
So what it does now, not sure if that is clear. If all are enabled (default), it does the followig
1. for all variables, set the default value if provided
2. look for a config file and overwrite the values of the variables set
3. look for the env variables and overwrite the values of the variables set
4. look for command line flags and overwrite the values of the variables set 

So yeah it's not possible to drop all variables from the file or env once there is a single command line flag. 

I think this behaviour is pretty ok, maybe it should just be explained better in the readme.

**Comment by buyology** [comment]
Semi-related to the above — as I understand it now, if you have specified `FileDefaultFilename`, it fails hard with `config file at … does not exist` if it cannot find a config file with the provided name (at the provided path).

Would it be possible to change this behaviour or at least add an option to proceed anyway to the env/flags?

(btw, thanks for a neat and lightweight lib — very refreshing.)

**Comment by raff** [comment]
Yes, actually this is exactly what I was asking. The application asks for config file or other options: if there is no file, I would like a way to proceed anyway with the other options/defaults.

**Comment by stevenroose** [comment]
Hmm, let me test that. I recently changed the behavior for looking for the
config file a bit. Maybe try update and try again?

I'll try myself later today.

**Comment by buyology** [comment]
@stevenroose the change in #9 looks good!

**Comment by stevenroose** [comment]
@raff Does #9 solve your issue?

**Comment by raff** [comment]
Yes, I think it does. Thanks!!!
