### ISSUE TITLE
default values in nested struct

### ISSUE THREAD

**Issue by costela** [stevenroose/gonfig#26]
Hey,

Either I misunderstood something fundamental about `gonfig`, or there might be a bug with default values and nested structs: the default values seem to be completely ignored.

```go
package main

import (
	"fmt"
	"github.com/stevenroose/gonfig"
)

var conf = struct {
	A string `default:"foo"`
	B struct {
		C string `default:"bar"`
	}
}{}

func main() {
	err := gonfig.Load(&conf, gonfig.Conf{})
	if err != nil {
		panic(err)
	}

	fmt.Printf("A: %s, C: %s\n", conf.A, conf.B.C)
}
```
And then:
```
$ go run tmp.go
A: foo, C:
```
(expected `A: foo, C: bar`)

This is a bit unexpected because setting the value explicitly works:
```
$ go run tmp.go --b.c baz
A: foo, C: baz
$ B_C=baz go run tmp. go
A: foo, C: baz
```

Am I missing something obvious?

**Comment by stevenroose** [comment]
That indeed seems like a bug. Hmm, long time since I worked on this.

Either way, I usually set the default values in the declaration of the conf variable, so probably that's why I didn't notice.

Like 
```go
type SubConf {
    C string
}
var conf = Conf {
    A string
    Sub SubConf
}{
    A: "foo",
    Sub: SubConf {
        C: "bar",
    }
}

func main() {
    err := gonfig.Load(&conf, gonfig.Conf{})
    ...
}
```

**Comment by stevenroose** [comment]
But I'll have to look into the actual bug too :)

**Comment by costela** [comment]
Turns out it was an easier fix than I expected. Not bad for a Friday! :)
