### ISSUE TITLE
ignored defaults for pointer types 

### ISSUE THREAD

**Issue by costela** [stevenroose/gonfig#30]
Hey Steven,

Got another problem with defaults in struct tags. The following doesn't work:
```go
var config = struct {
    foobar *SomeUnmarshableType `default:"somevalue"`
}
```

Problem seems to be in the `isZero` check, which checks the pointer value (instead of the _pointed_ value) and decides it has been set, thus ignoring the struct tag default.

PR for it coming in the next few seconds :wink:

Cheers

**Comment by stevenroose** [comment]
Hmm, it's cool to see someone explore the edges of possibilities :D I don't think I ever did pointers, tbh.
