### ISSUE TITLE
Add support of HJSON

### ISSUE THREAD

**Issue by chmike** [stevenroose/gonfig#5]
Could it be possible to add support of [hjson](https://hjson.org/) by mean of the [HJSON-go](https://github.com/hjson/hjson-go) package ? 

hjson is human friendly json. This means a json encoding more convenient for humans to read and write. The best way to use it is to convert the hjson string into json, and than use the json decoding. 

An alternate solution would be to support a string as config input instead of a file. This would allow users to any type of source for the config. It could be extracted from a database for instance.

**Comment by stevenroose** [comment]
An input string would not work together with giving flags to specify the
config file.

I might make encodings more generic by using an interface like `type
FileEncoding func(content []byte) (map[string]interface{}, error)` and then
define global vars for JSON, YAML and TOML and allow users to put a custom
encoding function.

Let me look into that tomorrow.

**Comment by stevenroose** [comment]
Look at this commit: https://github.com/stevenroose/gonfig/commit/c814583691ea0dbfd235701afd5d50f9033783a6

I think it's ok for you to specify a custom decoder for HJSON. I don't think HJSON is common enough to be worth it maintaining it in the package. 

You can create a function like here: https://github.com/stevenroose/gonfig/commit/c814583691ea0dbfd235701afd5d50f9033783a6#diff-3b7b9b0c1df08c66e0e7ffb8929051d1R23

**Comment by chmike** [comment]
The DecoderTryAll is a brute force solution.
Define an interface for ConfigDecoder functions and use the encoding type string as key. 
In the Init() function we may register the decoding type and function.

**Comment by stevenroose** [comment]
Well, TryAll is only used when no decoder is provided in Conf here: https://github.com/stevenroose/gonfig/commit/c814583691ea0dbfd235701afd5d50f9033783a6#diff-b67b03abee47ec66b6b9d0e2302a2576R35

So yes it's brute force last resort. I'm quite impartial for removing it and panicing if no decoder is provided in the Conf struct.

**Comment by stevenroose** [comment]
I believe this is solved.

gonfig supports custom config file decoders. F.e. for hjson, one could make one like this:
```go
// DecoderHJSON is an HJSON decoding function for config files.
var DecoderHJSON = func(c []byte) (map[string]interface{}, error) {
	var m map[string]interface{}
	if err := hjson.Unmarshal(c, &m); err != nil {
		return nil, fmt.Errorf("error parsing HJSON config file: %s", err)
	}

	return m, nil
}
```

And pass it to `Load` as follows:
```go
gonfig.Load(&config, gonfig.Conf{
    FileDecoder: DecoderHJSON,
}
```
