### ISSUE TITLE
Creating a release.

### ISSUE THREAD

**Issue by zbindenren** [stevenroose/gonfig#8]
Probably creating a release tag would be a good idea in order to work with deb, glide etc...

**Comment by stevenroose** [comment]
Sure. But I prefer to wait a little bit in order to settle on the interface.

This project is a week old, I'm Integrating it in some of my own projects
first to see what quirks come up :)

But sure, after that, I'll tag it with proper semver.

**Comment by stevenroose** [comment]
I've been using gonfig myself in several projects with quite a sizable configuration setup, so I will mark `v0.1.0`. This keeps the option open to change the interface still before going to 1.0.
